### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by zyb8543d** [ZRayZzz/flash-attention-v100#3]
```
FAILED: /data/disk2/ybZhang/ms-train/flash-attention/build/temp.linux-x86_64-cpython-38/kernel/fused_mha_kernel.o
/usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /data/disk2/ybZhang/ms-train/flash-attention/build/temp.linux-x86_64-cpython-38/kernel/fused_mha_kernel.o.d -I/data/disk2/ybZhang/ms-train/flash-attention/include -I/data/disk2/ybZhang/ms-train/cutlass/include -I/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/torch/include -I/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/torch/include/TH -I/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/ybZhang/miniconda3/envs/glm-m/include/python3.8 -c -c /data/disk2/ybZhang/ms-train/flash-attention/kernel/fused_mha_kernel.cu -o /data/disk2/ybZhang/ms-train/flash-attention/build/temp.linux-x86_64-cpython-38/kernel/fused_mha_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math -gencode arch=compute_70,code=sm_70 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=flash_attn_v100_cuda -D_GLIBCXX_USE_CXX11_ABI=0
/data/disk2/ybZhang/ms-train/flash-attention/kernel/fused_mha_kernel.cu(877): error: class "cute::TiledMMA<cute::MMA_Atom<cute::MMA_Traits<cute::SM70_8x8x4_F32F16F16F32_TN>>, cute::Layout<cute::tuple<cute::C<4>, cute::_4, cute::_1>, cute::tuple<cute::_1, cute::_4, cute::_0>>, cute::tuple<cute::Layout<cute::tuple<cute::_1, cute::_1>, cute::tuple<cute::_0, cute::_0>>, cute::Underscore, cute::Underscore>>" has no member "TiledShape_MNK"
          using MNK = typename MMA_TN::TiledShape_MNK;
                                       ^

1 error detected in the compilation of "/data/disk2/ybZhang/ms-train/flash-attention/kernel/fused_mha_kernel.cu".
[2/2] c++ -MMD -MF /data/disk2/ybZhang/ms-train/flash-attention/build/temp.linux-x86_64-cpython-38/kernel/fused_mha_api.o.d -pthread -B /home/ybZhang/miniconda3/envs/glm-m/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/data/disk2/ybZhang/ms-train/flash-attention/include -I/data/disk2/ybZhang/ms-train/cutlass/include -I/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/torch/include -I/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/torch/include/TH -I/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/ybZhang/miniconda3/envs/glm-m/include/python3.8 -c -c /data/disk2/ybZhang/ms-train/flash-attention/kernel/fused_mha_api.cpp -o /data/disk2/ybZhang/ms-train/flash-attention/build/temp.linux-x86_64-cpython-38/kernel/fused_mha_api.o -O3 -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=flash_attn_v100_cuda -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: 警告：command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2096, in _run_ninja_build
    subprocess.run(
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 151, in <module>
    setup(
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/command/install.py", line 87, in run
    self.do_egg_install()
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/command/install.py", line 139, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 110, in build
    self.run_command('build_ext')
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 91, in run
    _build_ext.run(self)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 871, in build_extensions
    build_ext.build_extensions(self)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
    self._build_extensions_serial()
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 252, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
    objects = self.compiler.compile(
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 684, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1774, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2112, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

```

**Comment by ZRayZzz** [comment]
你的cutlass版本是不是不对？我看里面有变量类型不对。
